# Site settings
title: Kay on the rails
email: iam@hannal.net
description: > # this means to ignore newlines until "baseurl:"
  Kay as known as Hannal walks on the rails
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.hannal.com" # the base hostname & protocol for your site
twitter_username: hannal
github_username: hannal
paginate: 2
plugins: [jekyll-paginate]

# Build settings
#markdown: kramdown
#markdown: redcarpet
redcarpet:
    extensions: [footnotes, tables]
#highlighter: pygments
highlighter: rouge
#highlighter: rdiscount

category_dir: _site/category
categories: [essay, start-with-django-lectures, start-with-django-webframework, kay-on-the-team, flaskon-startup-diary, devlife, game]

project_dir: _projects
